version: "3"
services:
  producer:
    image: employee-producer
    ports:
      - "8069:8080"
    networks:
      - consumer-producer    
  consumer:
    image: employee-consumer
    ports:
      - "8081:8091"
    networks:
      - consumer-producer
    depends_on:
      - producer
      
networks:
  consumer-producer:
      
 

